import themes from '../themes';

/**
 * 辅助函数：保留指定位数的小数
 * @param {number} num 数字
 * @param {number} precision 保留小数位数
 * @returns {string}
 */
const toFixed = (num, precision) => {
  return num.toFixed(precision);
};

/**
 * 生成计数器 SVG (新版本，支持更多参数)
 * @param {object} params 参数对象
 * @param {number} count 需要显示的数字
 * @param {string} [theme='moebooru'] 主题
 * @param {number} [padding=7] 数字总长度
 * @param {number} [prefix=-1] 前缀数字
 * @param {number} [offset=0] 数字间距偏移
 * @param {string} [align='top'] 对齐方式 (top/center/bottom)
 * @param {number} [scale=1] 缩放比例
 * @param {string} [pixelated='1'] 是否像素化
 * @param {string} [darkmode='auto'] 暗黑模式 (auto/0/1)
 * @returns {string} SVG 字符串
 */
function getCountImage(params) {
  let {
    count,
    theme = 'moebooru',
    padding = 7,
    prefix = -1,
    offset = 0,
    align = 'top',
    scale = 1,
    pixelated = '1',
    darkmode = 'auto'
  } = params;

  // 验证主题是否存在
  if (!themes[theme]) {
    theme = 'moebooru';
  }

  // 参数标准化
  padding = parseInt(Number(padding), 10);
  offset = parseFloat(Number(offset));
  scale = parseFloat(Number(scale));

  // 生成数字数组
  const countArray = count.toString().padStart(padding, '0').split('');

  // 添加前缀
  if (prefix >= 0) {
    countArray.unshift(...String(prefix).split(''));
  }

  // 添加_start和_end占位符（如果主题支持）
  if (themes[theme].hasOwnProperty('_start')) {
    countArray.unshift('_start');
  }
  if (themes[theme].hasOwnProperty('_end')) {
    countArray.push('_end');
  }

  const uniqueChars = [...new Set(countArray)];
  let x = 0;
  let y = 0;

  // 生成 SVG defs 部分
  const defs = uniqueChars.reduce((ret, cur) => {
    if (!themes[theme][cur]) return ret;

    const { width, height, images } = themes[theme];
    const uri = images[parseInt(cur) || cur]; // 处理数字和特殊字符

    let charWidth = width * scale;
    let charHeight = height * scale;

    y = Math.max(y, charHeight);

    return `${ret}
    <image id="${cur}" width="${toFixed(charWidth, 5)}" height="${toFixed(charHeight, 5)}" xlink:href="${uri}" />`;
  }, '');

  // 生成 SVG 使用部分
  const parts = countArray.reduce((ret, cur) => {
    if (!themes[theme][cur]) return ret;

    const { width, height } = themes[theme];
    let charWidth = width * scale;
    let charHeight = height * scale;

    let yOffset = 0;
    if (align === 'center') {
      yOffset = (y - charHeight) / 2;
    } else if (align === 'bottom') {
      yOffset = y - charHeight;
    }

    const image = `${ret}
    <use x="${toFixed(x, 5)}"${yOffset ? ` y="${toFixed(yOffset, 5)}"` : ''} xlink:href="#${cur}" />`;

    x += charWidth + offset;
    return image;
  }, '');

  // 修正最后一个元素的偏移
  x -= offset;

  // 样式处理
  const style = `
  svg {
    ${pixelated === '1' ? 'image-rendering: pixelated;' : ''}
    ${darkmode === '1' ? 'filter: brightness(.6);' : ''}
  }
  ${darkmode === 'auto' ? `@media (prefers-color-scheme: dark) { svg { filter: brightness(.6); } }` : ''}
  `;

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Moe Counter -->
<svg viewBox="0 0 ${toFixed(x, 5)} ${toFixed(y, 5)}" width="${toFixed(x, 5)}" height="${toFixed(y, 5)}" version="1.1" 
  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <title>Moe Counter</title>
  <style>${style}</style>
  <defs>${defs}
  </defs>
  <g>${parts}
  </g>
</svg>`;
}

/**
 * 原版生成计数器 SVG (保持兼容)
 * @param {number} count 需要显示的数字
 * @param {string} theme 主题
 * @param {number} length 数字总长度
 * @param {boolean} pixelated 是否像素化
 * @returns {string} SVG 字符串
 */
const getLegacyCountImage = (count, theme, length, pixelated) => {
  return getCountImage({
    count,
    theme,
    padding: length,
    pixelated: pixelated ? '1' : '0'
  });
};

export { getLegacyCountImage as getCountImage };
