import themes from '../themes';

/**
 * 辅助函数：保留指定位数的小数
 * @param {number} num 数字
 * @param {number} precision 保留小数位数
 * @returns {string}
 */
const toFixed = (num, precision) => {
  return num.toFixed(precision);
};

/**
 * 生成计数器 SVG
 * @param {number} count 需要显示的数字
 * @param {string} theme 主题
 * @param {number} length 数字总长度
 * @param {boolean} pixelated 是否像素化
 * @returns {string} SVG 字符串
 */
const getCountImage = (count, theme, length, pixelated) => {
  try {
    // 验证主题
    if (!themes[theme]) {
      theme = 'moebooru';
    }

    // 验证参数
    const countNum = Number(count) || 0;
    const lengthNum = Number(length) || 7;

    const countArray = countNum.toString().padStart(lengthNum, '0').split('');
    const uniqueChars = [...new Set(countArray)];

    let x = 0;
    let y = 0;

    const { width, height, images } = themes[theme];

    // 生成 defs 部分
    const defs = uniqueChars.reduce((ret, cur) => {
      const uri = images[cur];
      if (!uri) return ret;

      const charWidth = width;
      const charHeight = height;

      y = Math.max(y, charHeight);

      return `${ret}
      <image id="${cur}" width="${toFixed(charWidth, 5)}" height="${toFixed(charHeight, 5)}" xlink:href="${uri}" />`;
    }, '');

    // 生成使用部分
    const parts = countArray.reduce((ret, cur) => {
      const uri = images[cur];
      if (!uri) return ret;

      const charWidth = width;
      const charHeight = height;

      const image = `${ret}
      <use x="${toFixed(x, 5)}" xlink:href="#${cur}" />`;

      x += charWidth;
      return image;
    }, '');

    // 样式
    const style = `
    svg {
      ${pixelated ? 'image-rendering: pixelated;' : ''}
    }
    `;

    return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Moe Counter -->
<svg viewBox="0 0 ${toFixed(x, 5)} ${toFixed(y, 5)}" width="${toFixed(x, 5)}" height="${toFixed(y, 5)}" version="1.1" 
  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <title>Moe Counter</title>
  <style>${style}</style>
  <defs>${defs}
  </defs>
  <g>${parts}
  </g>
</svg>`;
  } catch (err) {
    console.error('Error generating SVG:', err);
    // 返回一个简单的错误 SVG
    return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="200" height="50" xmlns="http://www.w3.org/2000/svg">
  <text x="10" y="30" font-family="monospace" font-size="14">Error generating counter</text>
</svg>`;
  }
};

export { getCountImage };
